feat(auth-connect): add the getting started guide
ionic-enterprise/tutorials pull request #1
Opened 2023-09-12 20:51 UTC by kensodemann

2023-09-13 13:11 UTC, eric-horodyski reviewed
Now that we can display instructions and code side-by-side, does it make sense to trim down certain bits of instruction/explanation? For example:

> In the `capacitor.config.ts` file, change the `appId` to be something unique. The `appId` is used as the bundle ID. Therefore it should be a string that unique to your organization and application. We will use `io.ionic.gettingstartedangular` for this application. 

We could trim some of this paragraph since the reader would see the filename and changes reflected to their right:

> Change the `appId` to be something unique. The `appId` is used as the bundle ID. Therefore, it should be a string that is unique to your organization and application.

This is more food for thought than a request to make any changes.

2023-09-13 13:12 UTC, eric-horodyski approved these changes

2023-09-13 13:24 UTC, eric-horodyski requested changes

2023-09-13 13:24 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/angular/introduction.md
> +```
Wrap this in a `<CH.Code>` component and use the [rows](https://codehike.org/docs/ch-code#height) prop to adjust the height to just what the user needs highlighted. I tested with `<CH.Code rows={10}>` and it looks pretty good.

2023-09-13 13:24 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/angular/introduction.md
> +```
Wrap this in a `<CH.Code>` component and use the [rows](https://codehike.org/docs/ch-code#height) prop to adjust the height to just what the user needs highlighted. I tested with `<CH.Code rows={4}>` and it looks pretty good.

2023-09-13 13:26 UTC, kensodemann commented on docs/native-solutions/auth-connect/angular/introduction.md
> +```
Nice! I was actually wondering if there was a way to do that then forgot to ask.

2023-09-13 15:30 UTC, kensodemann commented on docs/native-solutions/auth-connect/angular/introduction.md
> +```
Done

2023-09-13 15:30 UTC, kensodemann commented on docs/native-solutions/auth-connect/angular/introduction.md
> +```
done

2023-09-13 15:34 UTC, kensodemann commented
> Now that we can display instructions and code side-by-side, does it make sense to trim down certain bits of instruction/explanation?

I trimmed that specific one. I was not sure if there were others you had in mind. In some cases I am doing this when we switch from one file to another in a multi-file set to make it more obvious that we have switched files.

Perhaps those should stay, not sure. Have a look.

If you have other specific cases you see, though, I am happy to address them.

2023-09-13 17:27 UTC, kensodemann commented on docs/native-solutions/auth-connect/angular/introduction.md
> +import { BehaviorSubject, Observable } from 'rxjs';
OK, I have fixed that... Switched to having an `isAuthenticated()`, which will work out better in the long run.

2023-09-19 14:46 UTC, jameson-w-taylor commented on docs/native-solutions/auth-connect/angular/introduction.md
> +Change the `appId` to be something unique. The `appId` is used as the [bundle ID](https://developer.apple.com/documentation/appstoreconnectapi/bundle_ids) / [application ID](https://developer.android
"...should be a string that unique...", should fix to say either "that's" or "that is"

2023-09-19 14:52 UTC, jameson-w-taylor commented on docs/native-solutions/auth-connect/angular/introduction.md
> +Auth Connect is now properly set up and initialized. We can move on to creating the basic log in and log out flow. Within this flow, and `AuthResult` is obtained during log in that represents our aut
"...and `AuthResult` is..." should be "an"

2023-09-19 14:54 UTC, jameson-w-taylor commented on docs/native-solutions/auth-connect/angular/introduction.md
> +For the `login()`, we need to pass both the `provider` and the `options` we established earlier. Note that we for the `setup()` call to resolve and that we store the result in our session variable.
"...that we for the...", should be "we wait for"

2023-09-19 14:56 UTC, jameson-w-taylor commented on docs/native-solutions/auth-connect/angular/introduction.md
> +Note that if you press the Login button while already logged in the login tag is closed immediately. This is expected behavior.
"...the login tag is...", should be "tab"

2023-09-19 14:57 UTC, jameson-w-taylor commented on docs/native-solutions/auth-connect/angular/introduction.md
> +This login and logout are working on the web. Build your application for mobile and try to run them there. You can an emulator or an actual device for this test.
"...can an emulator or...", should be "can use an emulator"

2023-09-19 15:03 UTC, jameson-w-taylor commented on docs/native-solutions/auth-connect/getting-started.md
> +- Create a basic authentication from from log in to log out.
"...authentication from from log...", remove extra "from"

2023-09-19 15:04 UTC, jameson-w-taylor commented on docs/native-solutions/auth-connect/getting-started.md
> +- Manage the authentication session that is represented in Auth Connect via a `AuthResult` object.
"...via a `AuthResult`...", should be "an"

2023-09-19 15:12 UTC, jameson-w-taylor requested changes
Added some inline comments for a few grammatical fixes.

2023-09-19 15:48 UTC, kensodemann commented on docs/native-solutions/auth-connect/angular/introduction.md
> +Change the `appId` to be something unique. The `appId` is used as the [bundle ID](https://developer.apple.com/documentation/appstoreconnectapi/bundle_ids) / [application ID](https://developer.android
Fixed

2023-09-19 15:49 UTC, kensodemann commented on docs/native-solutions/auth-connect/angular/introduction.md
> +Auth Connect is now properly set up and initialized. We can move on to creating the basic log in and log out flow. Within this flow, and `AuthResult` is obtained during log in that represents our aut
fixed

2023-09-19 15:50 UTC, kensodemann commented on docs/native-solutions/auth-connect/angular/introduction.md
> +For the `login()`, we need to pass both the `provider` and the `options` we established earlier. Note that we for the `setup()` call to resolve and that we store the result in our session variable.
fixed

2023-09-19 15:51 UTC, kensodemann commented on docs/native-solutions/auth-connect/angular/introduction.md
> +Note that if you press the Login button while already logged in the login tag is closed immediately. This is expected behavior.
Fixed

2023-09-19 15:53 UTC, kensodemann commented on docs/native-solutions/auth-connect/getting-started.md
> +- Manage the authentication session that is represented in Auth Connect via a `AuthResult` object.
Fixed

2023-09-19 15:55 UTC, kensodemann commented on docs/native-solutions/auth-connect/getting-started.md
> +When an authentication vendor, such as AWS Cognito, is configured, and application is created. This application includes several pieces of data that Auth Connect needs in order to communicate with it
Fixed. Also, the use of commas seemed excessive in this context so I removed them, but I am also open to other opinions on that.

2023-09-19 15:59 UTC, jameson-w-taylor approved these changes

2023-09-19 17:32 UTC, jameson-w-taylor approved these changes

2023-09-19 18:30 UTC, eric-horodyski requested changes
Looking really good, just a few grammatical changes and one highlighting change.

2023-09-19 18:30 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/angular/introduction.md
> +Change the `appId` to be something unique. The `appId` is used as the [bundle ID](https://developer.apple.com/documentation/appstoreconnectapi/bundle_ids) / [application ID](https://developer.android
This text uses `io.ionic.gettingstartedangular` as an App ID, but the code example uses `io.ionic.gettingstartedac`.

2023-09-19 18:30 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/angular/introduction.md
> +Auth Connect needs to know how to communicate with our Authentication vendor. You will likely need to get this information from the team that manages your cloud infrastructure.
Remove capitalization from the word "Authentication":

> Auth Connect needs to know how to communicate with our authentication vendor.

2023-09-19 18:30 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/angular/introduction.md
> +We need to perform a one-time setup with AuthConnect. Please refer to the [documentation](https://ionic.io/docs/auth-connect/interfaces/AuthConnectConfig) if you have any questions about the individu
Make "AuthConnect" two words:

> We need to perform a one-time setup with Auth Connect.

2023-09-19 18:30 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/angular/introduction.md
> +Test this in the web using the following credentials:
> Test this in the web

Change to "Test this _on_ the web" or "Test this in _your_ web _browser_"

2023-09-19 18:30 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/angular/introduction.md
> +This login and logout are working on the web. Build your application for mobile and try to run them there. You can use an emulator or an actual device for this test.
Remove the word "This":

> "Login and logout are working on the web."

2023-09-19 18:30 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/angular/introduction.md
> +```typescript tab1.page.ts focus=19,24,27:29
Add highlighting to LN13.

2023-09-19 19:54 UTC, kensodemann commented on docs/native-solutions/auth-connect/angular/introduction.md
> +Change the `appId` to be something unique. The `appId` is used as the [bundle ID](https://developer.apple.com/documentation/appstoreconnectapi/bundle_ids) / [application ID](https://developer.android
fixed

2023-09-19 19:55 UTC, kensodemann commented on docs/native-solutions/auth-connect/angular/introduction.md
> +Auth Connect needs to know how to communicate with our Authentication vendor. You will likely need to get this information from the team that manages your cloud infrastructure.
done

2023-09-19 19:56 UTC, kensodemann commented on docs/native-solutions/auth-connect/angular/introduction.md
> +We need to perform a one-time setup with AuthConnect. Please refer to the [documentation](https://ionic.io/docs/auth-connect/interfaces/AuthConnectConfig) if you have any questions about the individu
Done

2023-09-19 19:57 UTC, kensodemann commented on docs/native-solutions/auth-connect/angular/introduction.md
> +Test this in the web using the following credentials:
done

2023-09-19 19:57 UTC, kensodemann commented on docs/native-solutions/auth-connect/angular/introduction.md
> +This login and logout are working on the web. Build your application for mobile and try to run them there. You can use an emulator or an actual device for this test.
done

2023-09-19 19:59 UTC, kensodemann commented on docs/native-solutions/auth-connect/angular/introduction.md
> +```typescript tab1.page.ts focus=19,24,27:29
done

2023-09-19 20:24 UTC, eric-horodyski approved these changes

2023-09-19 20:39 UTC, merged