feat(AC): add current UI for Vue
ionic-enterprise/tutorials pull request #10
Opened 2023-11-29 22:59 UTC by kensodemann

2023-11-29 23:11 UTC, dtarnawsky commented on docs/native-solutions/auth-connect/vue/popup-vs-current.md
> +With `popup`, the authentication provider is opened in a new browser tab / window. This mode is the most consistent with how Auth Connect works on mobile where the authentication provider is displaye
"On the web, this This option" should be "On the web, this option"

2023-11-29 23:12 UTC, dtarnawsky commented on docs/native-solutions/auth-connect/vue/popup-vs-current.md
> +With `current`, the authentication provider is opened in the current windows, replacing your application. Your application will then be called with token information on the URL upon successful login.
"in the current windows" > "in the current window"

2023-11-30 12:58 UTC, kensodemann commented on docs/native-solutions/auth-connect/vue/popup-vs-current.md
> +With `current`, the authentication provider is opened in the current windows, replacing your application. Your application will then be called with token information on the URL upon successful login.
removed 's'

2023-11-30 12:59 UTC, kensodemann commented on docs/native-solutions/auth-connect/vue/popup-vs-current.md
> +If your application is distributed in a web context, it is worth considering using `current` for an improved user experience on web.
Fixed.

2023-11-30 14:04 UTC, dtarnawsky approved these changes

2023-11-30 16:09 UTC, jameson-w-taylor requested changes

2023-11-30 16:22 UTC, kensodemann commented on docs/native-solutions/auth-connect/vue/popup-vs-current.md
> +With `current`, the authentication provider is opened in the current window, replacing your application. Your application will then be called with token information on the URL upon successful login.
How about changing "called" to "restarted" and leaving the rest fundamentally the same?

2023-11-30 16:24 UTC, kensodemann commented on docs/native-solutions/auth-connect/vue/popup-vs-current.md
> +With `current`, this code will still work like this on mobile. However, on web our app is completely replaced by the
Updated as suggested.

2023-11-30 16:25 UTC, kensodemann commented on docs/native-solutions/auth-connect/vue/popup-vs-current.md
> +If there are no parameter, we will assume a logout and set the `authResult` to `null`.
fixed

2023-11-30 23:53 UTC, jameson-w-taylor commented on docs/native-solutions/auth-connect/vue/popup-vs-current.md
> +With `current`, the authentication provider is opened in the current window, replacing your application. Your application will then be called with token information on the URL upon successful login.
I think that would be fine

2023-11-30 23:54 UTC, jameson-w-taylor approved these changes

2023-12-01 13:42 UTC, merged