feat(digitial-passes): Tutorial on Apple Wallet digital passes
ionic-enterprise/tutorials pull request #11
Opened 2023-11-30 20:08 UTC by dtarnawsky

This is a tutorial on creating and adding digital passes with Apple Wallet. Some details are there for Google Wallet which will be fleshed out later when I have plenty of time to create a working example with Google Wallet.

2023-12-01 18:29 UTC, kensodemann approved these changes

2023-12-01 18:30 UTC, eric-horodyski requested changes

2023-12-01 18:30 UTC, eric-horodyski commented on docs/integrations/digitial-passes/apple-wallet-passes/creating.md
> +```json
You can display code file names with CodeHike. They adjust MDX in such a way that the following works without using any specific CodeHike components

```
```json models/pass.json
```

2023-12-05 17:28 UTC, dtarnawsky commented
> The only question I had was whether we should like to `capacitor-pass-to-wallet`, but then I went to their NPMJS entry, and there isn't really much out there of use, so meh... 🤷🏻‍♂️
> 
> LGTM

I've added a link to the repo for the plugin.

2023-12-05 17:29 UTC, dtarnawsky commented on docs/integrations/digitial-passes/apple-wallet-passes/adding.md
> +```
Thanks, fixed it (was a copy of the function written in Angular but redid it to be more generic)

2023-12-05 18:07 UTC, eric-horodyski approved these changes

2023-12-05 20:18 UTC, marlon-ionic commented
LGTM…It's not a huge deal, but I kinda think the steps should be flipped so `Creating Passes` is first. I understand that the `Adding Passes` step is simpler to follow, but If a user has to rely on this tutorial, I think they should be able to follow the steps in the order provided to complete the process.

2023-12-05 20:22 UTC, marlon-ionic approved these changes

2023-12-07 17:29 UTC, merged