Terminal feat(AC): add current UI for React
ionic-enterprise/tutorials pull request #12
Opened 2023-11-30 22:14 UTC by kensodemann

2023-11-30 22:15 UTC, kensodemann commented
Note: this is based on the Vue one with very minor tweaks, so the biggest thing to make sure of is that I have not left any Vue-isms in this... But a review of the React strategy wouldn't be bad either.

2023-12-01 17:33 UTC, eric-horodyski requested changes

2023-12-01 17:33 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/react/popup-vs-current.md
> +  - If parameters do not exist, this was a logout and the session vault is cleared.
Add a bullet for redirecting the user past this page.

2023-12-01 20:37 UTC, kensodemann commented on docs/native-solutions/auth-connect/react/popup-vs-current.md
> +different than the mobile implementation, it also means that special code is needed to handle it.
They would do this after going through the main getting started tutorial, so they should know basically how the flow is already working, so this is likely ok.

I'll leave it as-is for now, but we can always update later if customers are confused in some way.

2023-12-01 20:43 UTC, kensodemann commented on docs/native-solutions/auth-connect/react/popup-vs-current.md
> +  - If parameters do not exist, this was a logout and the session vault is cleared.
Done. Handled in both React and Vue.

2023-12-01 22:06 UTC, kensodemann commented on docs/native-solutions/auth-connect/react/popup-vs-current.md
> +  }
Updated as suggested.

2023-12-05 19:40 UTC, rjtwohey requested changes

2023-12-05 19:40 UTC, rjtwohey commented on docs/native-solutions/auth-connect/react/popup-vs-current.md
> +    web: { uiMode: 'current', authFlow: 'PKCE' },
Should this be `{ uiMode: 'popup', ... }` instead based off  

>  Note that it is using a `uiMode` of `popup`.

2023-12-05 19:43 UTC, kensodemann commented on docs/native-solutions/auth-connect/react/popup-vs-current.md
> +    web: { uiMode: 'current', authFlow: 'PKCE' },
No, because the instructions for this step is:

> Change the `uiMode` to `current`.

2023-12-05 19:45 UTC, rjtwohey approved these changes

2023-12-05 19:52 UTC, merged