feat(pdfs): tutorial for PDF or file download, share and open
ionic-enterprise/tutorials pull request #20
Opened 2023-12-08 19:22 UTC by dtarnawsky

This tutorial covers downloading PDF or other files, sharing the file and opening it.

2024-01-04 14:52 UTC, jameson-w-taylor requested changes

2024-01-04 14:52 UTC, jameson-w-taylor commented on docs/integrations/pdfs/download.md
> +In this example we display the progress bar only if we are `downloading`. We need to set the `value` property to a value between 0 and 1 which is done using the `progress` event:
I tend to overdo this, but I like to provide links to any documentation the first time I reference something. So with this being the first mention of the `progress` event, maybe wrap it with a link out to that [doc](https://capacitorjs.com/docs/apis/filesystem#addlistenerprogress-)?

2024-01-04 14:52 UTC, jameson-w-taylor commented on docs/integrations/pdfs/download.md
> +- We calculate the progress by dividing `bytes` by `contentLength` from the `ProgressStatus` object that is given when the `progress` event occurs.
Same as the above comment, but add [link](https://capacitorjs.com/docs/apis/filesystem#progressstatus) for `ProgressStatus`

2024-01-04 15:22 UTC, dtarnawsky commented on docs/integrations/pdfs/download.md
> +In this example we display the progress bar only if we are `downloading`. We need to set the `value` property to a value between 0 and 1 which is done using the `progress` event:
Thanks, I've made that change.

2024-01-04 15:22 UTC, dtarnawsky commented on docs/integrations/pdfs/download.md
> +- We calculate the progress by dividing `bytes` by `contentLength` from the `ProgressStatus` object that is given when the `progress` event occurs.
Thanks, I've made that change.

2024-01-04 15:25 UTC, jameson-w-taylor approved these changes

2024-01-04 18:05 UTC, eric-horodyski requested changes

2024-01-04 18:05 UTC, eric-horodyski commented on docs/integrations/pdfs/download.md
> +- We use `ngZone` to tell Angular that the we are making changes to something in the view (the `progress` variable). This is needed because any events that are emitted from Capacitor are not captured
I would:

- Link to the component
- Mention that the code sample is for Angular, using the new view syntax
- Advise the reader that the NgZone stuff is Angular specific, and they should adapt the code to their framework if they aren't using Angular

2024-01-05 20:41 UTC, dtarnawsky commented on docs/integrations/pdfs/download.md
> +4. Use Capacitor's [`DownloadFile`](https://capacitorjs.com/docs/apis/filesystem#downloadfile) method
Thanks, this has been updated.

2024-01-05 20:41 UTC, dtarnawsky commented on docs/integrations/pdfs/download.md
> +The best approach is to use the `DownloadFile` method.
Thanks, this has been updated.

2024-01-05 20:41 UTC, dtarnawsky commented on docs/integrations/pdfs/download.md
> +- We use `ngZone` to tell Angular that the we are making changes to something in the view (the `progress` variable). This is needed because any events that are emitted from Capacitor are not captured
Thanks, this has been updated.

2024-01-08 14:12 UTC, merged