feat(play-integrity): Using the Play Integrity API
ionic-enterprise/tutorials pull request #24
Opened 2024-01-17 00:48 UTC by dtarnawsky

2024-01-19 15:45 UTC, jameson-w-taylor requested changes

2024-01-19 15:45 UTC, jameson-w-taylor commented on docs/mobile-security/play-integrity.md
> +Using the Play Integrity API is a powerful way to ensure that API services that you expose are only accessed by your mobile application. This can prevent API access by bots, scripts etc which is a po
I think maybe the second sentence should be reworded so "powerful" isn't used twice?

"This can prevent API access by bots, scripts, etc, and is a great way to protect your users and services."

2024-01-19 15:45 UTC, jameson-w-taylor commented on docs/mobile-security/play-integrity.md
> +## Adding to your App
I think this section has a few topics that feel like they're in reverse order.
Possibly break some of the prerequisites out into their own section, or reorder these steps to better reflect the order they're needed:

1. Link Cloud Project
2. Install play-integrity plugin
3. Describe parameters needed
4. Call plugin code snippet
5. Describe what Integrity Token is and how we'll use it

2024-01-19 15:45 UTC, jameson-w-taylor commented on docs/mobile-security/play-integrity.md
> +The Play Integrity API is one layer in the overall security with your App. Other topics you may like to explore include Root Kit Detection, Code Obsfucation, SSL Pinning, Security provider updates an
"security with" should be "security of"

2024-01-19 18:06 UTC, dtarnawsky commented on docs/mobile-security/play-integrity.md
> +## Adding to your App
Thanks, I've applied these changes

2024-01-19 18:07 UTC, dtarnawsky commented on docs/mobile-security/play-integrity.md
> +The Play Integrity API is one layer in the overall security with your App. Other topics you may like to explore include Root Kit Detection, Code Obsfucation, SSL Pinning, Security provider updates an
Thanks, I've applied this change

2024-01-19 18:13 UTC, jameson-w-taylor approved these changes

2024-01-23 22:13 UTC, tomionic commented on docs/mobile-security/play-integrity.md
> +This means that you should not request and validate on every API call, instead on first startup or as part of a login process.
every API call, "but" instead on "the" first startup

2024-01-23 22:13 UTC, tomionic commented on docs/mobile-security/play-integrity.md
> +An Integrity Token is not a guarantee of device being legitimate. To get a verdict on whether a device is "ok" you must check the token on your backend.
An Integrity Token is not a guarantee "that the device is legitimate."

2024-01-23 22:13 UTC, tomionic commented on docs/mobile-security/play-integrity.md
> +For this tutorial we are using a Cloudflare Worker as our backend.
Consider adding a comma (,) after "tutorial"

2024-01-23 22:13 UTC, tomionic commented on docs/mobile-security/play-integrity.md
> +- This file is a secret and in our [Sample Project](https://github.com/ionic-enterprise/play-integrity) we upload it to Cloudflare as an environment variable (we call it `GOOGLE_CLOUD_CREDENTIALS`).
This bullet point has a period (.) and the rest should not. This should be consistent here and throughout the entire page.

2024-01-23 22:13 UTC, tomionic commented on docs/mobile-security/play-integrity.md
> +- `env.PACKAGE_NAME` is a variable which is our Android app's package name.
is a variable "that" is our Android app's package name.

2024-01-23 22:13 UTC, tomionic commented on docs/mobile-security/play-integrity.md
> +- `response` is a json object which gives us the verict of whether the mobile application client looks legitimate.
`response` is a "JSON" object "that" gives us the "verdict" of whether the mobile application client looks legitimate.

2024-01-23 22:13 UTC, tomionic commented on docs/mobile-security/play-integrity.md
> +Based on this response's `appLicensingVerdict`, `appRecognitionVerdict`, `deviceRecognitionVerdict` we make a judgement call as to whether we think this device should pass.
`appLicensingVerdict`, `appRecognitionVerdict`, "and" `deviceRecognitionVerdict` we make a "judgment" call as to whether we think this device should pass.

2024-01-23 22:13 UTC, tomionic commented on docs/mobile-security/play-integrity.md
> +For example this code returns a status code `200` back to the mobile app if it looks ok, otherwise a status code of `401`.
consider adding a comma (,) after "example"

2024-01-23 22:13 UTC, tomionic commented on docs/mobile-security/play-integrity.md
> +- **What about QA/Dev testing?** - Your application may want to have different rules for checking the verdict when it is in a staging/dev environment. For example you may allow `UNRECOGNIZED_VERSION`
consider adding a comma (,) after "example"

2024-01-25 03:39 UTC, merged