feat(device-check): Using the Device Check API
ionic-enterprise/tutorials pull request #28
Opened 2024-01-26 19:29 UTC by dtarnawsky

On an iOS device you can use [Device Check](https://developer.apple.com/documentation/devicecheck) to help reduce fraudulent use of your services by managing:
- [Device State](#device-state).
- [Asserting App Integrity](#asserting-app-integrity).

This tutorial covers how to get Device State working.

2024-01-31 14:46 UTC, kensodemann requested changes

2024-01-31 14:46 UTC, kensodemann commented on docs/mobile-security/device-check.md
> +### Asserting App Integrity
Is "Asserting App Integrity" supposed to be a child of "Device State"?

The bullet list above and the verbiage leading up to this would indicate a sibling relationship in the doc rather than the parent-child relationship we have here, so seeing this as a child was somewhat jarring, which is why I am asking.

2024-01-31 15:06 UTC, rjtwohey commented on docs/mobile-security/device-check.md
> +- **Does Device State survive uninstalling the App?** - Yes, so be sure to store only relevant information. For example, maybe your App has a purchase for a paid plan per device. You can use a bit fl
My question that stems from this one is "Is there a way to remove data device state?"

2024-01-31 16:15 UTC, dtarnawsky commented on docs/mobile-security/device-check.md
> +      const response: HttpResponse = await CapacitorHttp.post({
I wanted to emphasize SSL Pinning working hand in hand with Capacitor HTTP when I get to adding that as a tutorial. I also wanted to avoid the CORs conversation with anyone using the sample project and needing to explain the flag in Capacitor config. For me this was the easiest way to describe making the HTTP call.

2024-01-31 16:29 UTC, dtarnawsky commented on docs/mobile-security/device-check.md
> +- **Does Device State survive uninstalling the App?** - Yes, so be sure to store only relevant information. For example, maybe your App has a purchase for a paid plan per device. You can use a bit fl
Added this question and answer to the docs.

2024-01-31 17:02 UTC, jameson-w-taylor requested changes

2024-01-31 19:07 UTC, dtarnawsky commented on docs/mobile-security/device-check.md
> +1. [Install the Device Check Plugin](#install-the-device-check-plugin)
That would put "Implementing Device State" under "asserting app integrity" which is not the case.

2024-01-31 20:04 UTC, jameson-w-taylor commented on docs/mobile-security/device-check.md
> +1. [Install the Device Check Plugin](#install-the-device-check-plugin)
You can't nest the 5 steps as children of the device state section like how the cloudflare worker and verify token sections are nested for accepting token in backend?

2024-01-31 20:11 UTC, dtarnawsky commented on docs/mobile-security/device-check.md
> +1. [Install the Device Check Plugin](#install-the-device-check-plugin)
Ok, i've updated it, I misunderstood the first comment, sorry

2024-01-31 20:15 UTC, jameson-w-taylor commented on docs/mobile-security/device-check.md
> +1. [Install the Device Check Plugin](#install-the-device-check-plugin)
No worries.

Also just to nitpick this change, the 2 subsections of "accepting token in backend" are no longer nested as subsections of that step like they were previously so they'll need 4 #'s now...

2024-01-31 22:24 UTC, kensodemann approved these changes
Changes LGTM

2024-02-01 14:35 UTC, jameson-w-taylor approved these changes

2024-02-01 14:37 UTC, merged