feat(portals): iOS & web onboarding
ionic-enterprise/tutorials pull request #31
Opened 2024-02-07 17:12 UTC by eric-horodyski

2024-02-14 23:14 UTC, kensodemann requested changes
I have not reviewed the iOS bit but wanted to get these comments out there. I'll do another review with the iOS bits later.

2024-02-14 23:14 UTC, kensodemann commented on docs/portals/training/web/04-capacitor-plugin.md
> +4. Analytics should be logged when the web app is accessed through mobile or on the web.
A couple of items here:

1. Should vs. Shall: the former sounds like a feature request the latter sounds like a requirement
2. The first two requirements as worded very much sound like feature requests or deficiency reports rather than requirments.

I would do something more like:

1. The ability to log navigation to a new screen shall exist.
2. The ability to log specified actions taken in the app shall exist.
3. Every analytic entry shall track the platform the log occurred on.
4. Analytics shall be logged when the web app is accessed through mobile or on the web.

2024-02-14 23:14 UTC, kensodemann commented on docs/portals/training/web/04-capacitor-plugin.md
> +Authoring a Capacitor plugin is ideal in this case. The functionality of a Capacitor plugin is specified by a TypeScript API, which iOS, Android, and web developers write platform-specific implementa
> The functionality of a Capacitor plugin is specified by a TypeScript API, which iOS, Android, and web developers write platform-specific implementations adhering to.

The way that sentence is structured is odd, and it makes the reader re-read the first half to make sense of the second half.

Maybe something like:

The functionality of a Capacitor plugin is specified by a TypeScript API. Android, iOS, and web developers create platform-specific implementations that adhere to the defined API.

2024-02-14 23:14 UTC, kensodemann commented on docs/portals/training/web/04-capacitor-plugin.md
> +<Admonition type="info">
Another one that looks weird in a scrollycoding

2024-02-14 23:14 UTC, kensodemann commented on docs/portals/training/web/04-capacitor-plugin.md
> +Save the code, then tap either the plus icon or an individual expense's edit (pencil) icon. If you were to monitor network traffic (optional), you would notice requests sent to an analytics endpoint.
Active voice would be better. Example:

"If you monitor network traffic (optional), you will notice requests sent..."

2024-02-14 23:14 UTC, kensodemann commented on docs/portals/training/web/04-capacitor-plugin.md
> +All works when the plugin runs on a mobile platform, but if you navigate to `http://localhost:5173` you will encounter the following error:
"Everything works..." reads better than "All works..."

2024-02-15 12:34 UTC, kensodemann requested changes
iOS is complete.

Note that my review focused on wording and phrasing as opposed to any technical aspect of the training itself.

I'll do a separate dry-run of the training at some point after it is available.

2024-02-15 14:01 UTC, eric-horodyski commented on docs/portals/training/web/01-getting-started.md
> +    Coming soon!
I like the way the Admonition looks there!

2024-02-15 14:03 UTC, eric-horodyski commented on docs/portals/training/web/03-pub-sub.md
> +<Admonition type="info" title="Best Practice">
I removed the Admonition; the content isn't critical enough that the reader _needs_ a visual cue to make sure they don't miss it.

2024-02-15 14:04 UTC, eric-horodyski commented on docs/portals/training/web/02-initial-context.md
> +<Admonition type="info" title="Best Practice">
See above. I don't think it looks too jarring, but the content I've been putting in Admonitions within a scrolly-code isn't critical to have a "can't miss" UX.

2024-02-15 14:04 UTC, eric-horodyski commented on docs/portals/training/web/04-capacitor-plugin.md
> +Authoring a Capacitor plugin is ideal in this case. The functionality of a Capacitor plugin is specified by a TypeScript API, which iOS, Android, and web developers write platform-specific implementa
Fixed, thanks!

2024-02-15 14:04 UTC, eric-horodyski commented on docs/portals/training/web/04-capacitor-plugin.md
> +<Admonition type="info">
👍

2024-02-15 14:04 UTC, eric-horodyski commented on docs/portals/training/web/04-capacitor-plugin.md
> +Save the code, then tap either the plus icon or an individual expense's edit (pencil) icon. If you were to monitor network traffic (optional), you would notice requests sent to an analytics endpoint.
👍

2024-02-15 14:04 UTC, eric-horodyski commented on docs/portals/training/web/04-capacitor-plugin.md
> +All works when the plugin runs on a mobile platform, but if you navigate to `http://localhost:5173` you will encounter the following error:
👍

2024-02-15 14:05 UTC, eric-horodyski commented on docs/portals/training/ios/01-getting-started.md
> +After setting up the project and registering your Portals product key, you can now take advantage of the Portals iOS library. In the next step of this module, you will create a Portal and use the Por
Fixed, thanks!

2024-02-15 14:06 UTC, eric-horodyski commented on docs/portals/training/ios/04-dismissing-the-portal.md
> +    WebAppView(metadata: WebApps.metadata[0])
Thanks so much for figuring out what the issue was! It's fixed now.

2024-02-15 14:06 UTC, eric-horodyski commented on docs/portals/training/ios/04-dismissing-the-portal.md
> +The pub/sub mechanism available within the Portals library is ideal for simple use cases, such as allowing a web app presented through a Portal to request native navigation. In the next step of this
Fixed, thanks!

2024-02-15 14:06 UTC, eric-horodyski commented on docs/portals/training/ios/05-creating-plugin.md
> +1. There should be the ability to log when a user navigates to a new screen.
Fixed, thanks!

2024-02-15 22:25 UTC, kensodemann approved these changes
Everything I had seem before seems to have been adequately addressed. This LGTM.

2024-02-16 14:01 UTC, merged

2024-02-27 20:59 UTC, mattrein reviewed
Overall looks great!
My comments are pretty specific, feel free to just close any that you don't think are useful.

2024-02-27 20:59 UTC, mattrein commented on docs/portals/training/web/03-pub-sub.md
> +The back button is still visible when you visit `http://localhost:5173` on a web browser. That's OK for the purposes of this training, but in a production scenario you may want to use platform detect
Assuming these people are new to Capacitor Plugins, a link to the platform plugin might be helpful.

2024-02-27 20:59 UTC, mattrein commented on docs/portals/training/web/04-capacitor-plugin.md
> +<a href="https://ionic.io/docs/portals/choosing-a-communication#capacitor-plugins" target="_blank">Capacitor plugins</a> provide a practical approach to structured communication through a Portal. The
most ? capacitor plugins to be used?

2024-02-27 20:59 UTC, mattrein commented on docs/portals/training/web/04-capacitor-plugin.md
> +As a web developer, your responsibility includes implementing a Capacitor plugin for the web. In the following section, you will write the web implementation of the analytics plugin to meet the requi
your responsibility includes implementing a Capacitor plugin for the web
might be clearer as
your responsibility is to author the web implementation of a Capacitor Plugin.

The former reads a little bit like the web implementation is a Capacitor plugin.
Not sure if that makes sense.

2024-02-28 17:16 UTC, eric-horodyski commented on docs/portals/training/ios/03-passing-initial-context.md
> +Depending on your authentication configuration, it is possible that a session becomes stale after a user signs in but before they launch a Portal. It's recommended to pass web apps information needed
This is a very valid point. I've removed the Best Practice; I would like to discuss this (to the public) in a different document.

2024-02-28 17:44 UTC, eric-horodyski commented on docs/portals/training/ios/04-dismissing-the-portal.md
> +The pub/sub mechanism available within the Portals library is ideal for simple use cases, such as allowing a web app presented through a Portal to request native navigation. However, it is not suitab
I would if the documentation was broken down that way, but the docs are structured to show code samples for subscribing using either web or native and below that examples of how to publish using either web or native.

2024-02-28 17:59 UTC, eric-horodyski commented on docs/portals/training/ios/05-creating-plugin.md
> +<a href="https://ionic.io/docs/portals/choosing-a-communication#capacitor-plugins" target="_blank">Capacitor plugins</a> provide a practical approach to structured communication through a Portal. The
I've landed on "allowing Capacitor plugins to be used" and hope to leave it intentionally vague in the event we find out certain plugins can't be used (from the community or otherwise).

2024-02-28 19:33 UTC, eric-horodyski commented on docs/portals/training/ios/06-dynamic-portal-view.md
> +You now have the tools in place to start integrating Portals into any iOS app. Happy coding!! 🤓
I was planning on keeping this separate and putting something else together to guide devs on building native artifacts to pass to web devs. I'm waiting until the Android portion of the CLI is complete before doing that