feat(IV): add IV getting started guide for react
ionic-enterprise/tutorials pull request #32
Opened 2024-02-12 20:44 UTC by jon-ionic

Companion project available here: https://github.com/ionic-enterprise/tutorials-and-demos-react/pull/3

2024-02-13 18:03 UTC, kensodemann approved these changes
This LGTM, but the two React experts that you have on here really need to review it.

2024-02-13 19:27 UTC, eric-horodyski commented on docs/native-solutions/identity-vault/react/getting_started.md
> +**Important:** awaiting the completion of initialization in this manner is a best-practice that should always
Just an optional note on jazzing up this important notice. We can use the `<Admonition />` tag to mark up admonitions. I would use "warning" here, which would require two steps:

1. `import Admonition from '@theme/Admonition';` after LN5
2. Use the component like so:

```tsx
<Admonition type="warning">
Awaiting the completion of initialization in this manner is a best-practice that should always be followed.
</Admonition>
```

2024-02-13 19:28 UTC, eric-horodyski commented on docs/native-solutions/identity-vault/react/getting_started.md
> +In this section, we created a vault using the key io.ionic.gettingstartediv. Our vault is a "Secure Storage" vault, which means that the information we store in the vault is encrypted in the keychain
Place "io.ionic.gettingstartediv" in backticks (`) to render it as code.

2024-02-13 19:30 UTC, eric-horodyski commented on docs/native-solutions/identity-vault/react/getting_started.md
> +required. You may be tempted to just make the `useSessionVault`'s `vault` value public and then use the Identity Vault
I'm confused as to what `useSessionVault` refers to here.

2024-02-13 19:32 UTC, eric-horodyski commented on docs/native-solutions/identity-vault/react/getting_started.md
> +or simulated) and re-install it. In the web, you can close the running tab and open new one.
"In the web" should be "On the web".

2024-02-13 19:35 UTC, eric-horodyski commented on docs/native-solutions/identity-vault/react/getting_started.md
> +**Note:** We will address locking and unlocking a vault later in this tutorial.
You can spice this note up as well using `<Admonition />`. The possible display types can be found in the [documentation](https://docusaurus.io/docs/markdown-features/admonitions). Just note the triple-colon syntax (:::) doesn't work for some reason.

2024-02-13 19:37 UTC, eric-horodyski commented on docs/native-solutions/identity-vault/react/getting_started.md
> +```typescript src/util/session-vault.ts focus=6,67:71
I would remove the focus on the import (LN6). While important, readers may not realize they should be scrolling down to see what to do for LNs 67-71. Most modern IDEs will yell at them if they miss the import, so my opinion is that it should be the secondary focus of this code step and isn't critical if the reader misses it.

2024-02-13 19:57 UTC, jon-ionic commented on docs/native-solutions/identity-vault/react/getting_started.md
> +required. You may be tempted to just make the `useSessionVault`'s `vault` value public and then use the Identity Vault
Ah, a lot of this was copied and pasted from the Vue tutorial. I read through and thought I caught all the Vue-specific items but I missed this. Thanks for catching.

2024-02-13 20:10 UTC, jon-ionic commented on docs/native-solutions/identity-vault/react/getting_started.md
> +**Important:** awaiting the completion of initialization in this manner is a best-practice that should always
Great to know, thank you!

2024-02-13 20:16 UTC, eric-horodyski approved these changes
LGTM

2024-02-13 20:34 UTC, merged

2024-02-13 20:56 UTC, jameson-w-taylor requested changes

2024-02-13 20:56 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/react/getting_started.md
> +In order to install Identity Vault, you will need to use `ionic enterprise register`
I think this should be reworded a little to be like this instead:
> ... need to use the `ionic enterprise register` command to [register your product key](https://ionic.io/docs/enterprise-starter/enterprise-key).

2024-02-13 20:56 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/react/getting_started.md
> +- `vault-factory`: Builds either a `Vault` or `BrowserVault` depending on the whether our application is running in a web or web-native context.
It might be nice to link out to the IV docs for these Vault classes, and maybe quickly mention that the `BrowserVault` is only a mock when running on the web and provides no security as there is none available in that context.

2024-02-13 20:56 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/react/getting_started.md
> +### Store a Vault
I think this is supposed to be "Store a Value"

2024-02-13 20:56 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/react/getting_started.md
> +  vault.setValue('session', newSession);
`setValue` should be `await`ed here, since `storeSession` is marked `async`.
I don't think functionally this has much of a difference, so maybe there's a reason it's not?

2024-02-13 20:56 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/react/getting_started.md
> +is stored. We can get the current session data using `useSyncExternalStore`.
I usually try to avoid the word "use" or "using" before a hook name in a sentence, because it sounds a bit awkward. Maybe consider using "with" instead?
>... session data with `useSyncExternalStore`.

2024-02-13 20:56 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/react/getting_started.md
> +- `clear`: Clear all of the data stored in the vault and remove the vault from the keystore / keychain.
When describing APIs, I like to link out to the documentation.
Maybe consider changing `clear` to be [clear](https://ionic.io/docs/identity-vault/classes/vault#clear)

2024-02-13 20:56 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/react/getting_started.md
> +- `removeValue`: Clear just the data stored with the specified key.
Same as above, `removeValue` to [removeValue](https://ionic.io/docs/identity-vault/classes/vault#removevalue)

2024-02-13 20:56 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/react/getting_started.md
> +    since the vault had been removed.
The previous bullet point just said the Vault will not be removed.
I think this means to say value instead of vault?

2024-02-13 20:56 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/react/getting_started.md
> +  const type =
A nested ternary is a rough choice here, while it helps with brevity I'd refactor this for readability sake. Especially with another multiline ternary, although just a single one, soon to be added on the second line shortly...this will start to clutter quickly I think.

2024-02-13 20:56 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/react/getting_started.md
> +- "Use In Secure Storage": The session data is in the vault, but is not locked.
This should be "Use Secure Storage"

2024-02-13 20:56 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/react/getting_started.md
> +We can manually lock our vault, but it would be nice if the vault locked for us if the application was in the background for a period of time. We can accomplish this by doing two actions when initial
I'm not sure if this is the appropriate place to mention it, but this functionality will lock the vault on app startup if the configured time has passed (not while backgrounded). But with the new queueing this distinction might not be as necessary as it used to be. I can't remember if that build is released yet or not though.

2024-02-13 21:25 UTC, jon-ionic commented on docs/native-solutions/identity-vault/react/getting_started.md
> +  vault.setValue('session', newSession);
Ah great catch. No reason for not await-ing it, just missed that one. Thanks!

2024-02-13 21:48 UTC, jon-ionic commented on docs/native-solutions/identity-vault/react/getting_started.md
> +- `vault-factory`: Builds either a `Vault` or `BrowserVault` depending on the whether our application is running in a web or web-native context.
Great point. Do you think this is good wording?
```
- `vault-factory`: Builds either a [`Vault`](https://ionic.io/docs/identity-vault/classes/vault) or [`BrowserVault`](https://ionic.io/docs/identity-vault/classes/browservault) depending on the whether our application is running in a web or web-native context. The `BrowserVault` only mimics the basic behavior of the `Vault` for the purpose of running on the web and provides no security, as there as none available in the browser context.
- `session-vault`: Manages the vault and its contents.
```

2024-02-13 21:54 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/react/getting_started.md
> +  const type =
Maybe something like this?

```ts
export const updateUnlockMode = async (mode: UnlockMode): Promise<void> => {
  const newConfig = { ...(valut.config as IdentityVaultConfig) };

  switch (mode) {
    case 'BiometricsWithPasscode': {
      newConfig.type = VaultType.DeviceSecurity;
      newConfig.deviceSecurityType = DeviceSecurityType.Both;
      break;
    }
    case 'InMemory': {
      newConfig.type = VaultType.InMemory;
      newConfig.deviceSecurityType = DeviceSecurityType.None;
      break;
    }
    default: {
      newConfig.type = VaultType.SecureStorage;
      newConfig.deviceSecurityType = DeviceSecurityType.None;
      break;
    }
  }

  await vault.updateConfig({
    ...(vault.config as IdentityVaultConfig),
    type,
    deviceSecurityType,
  });
};
```

2024-02-14 16:19 UTC, jon-ionic commented on docs/native-solutions/identity-vault/react/getting_started.md
> +We can manually lock our vault, but it would be nice if the vault locked for us if the application was in the background for a period of time. We can accomplish this by doing two actions when initial
Updated the phrasing to suggest that the vault locks after being in the background rather than locking while it's in the background. I confirmed that the queueing feature is still in dev, so I'm not quite sure how to incorporate that into this tutorial. Does this phrasing sound better?

> We can manually lock our vault, but it would be nice if the vault locked for us after the application has been in the background for a period of time.

2024-02-14 16:24 UTC, kensodemann commented on docs/native-solutions/identity-vault/react/getting_started.md
> +We can manually lock our vault, but it would be nice if the vault locked for us if the application was in the background for a period of time. We can accomplish this by doing two actions when initial
I like the new wording FWIW.

Note that if you make the working change here, please also update the Angular and Vue versions of this tutorial to use the same wording as whatever you and Jameson work out.

2024-02-14 20:35 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/react/getting_started.md
> +- `vault-factory`: Builds either a `Vault` or `BrowserVault` depending on the whether our application is running in a web or web-native context.
I would just change the order of "... in a web or web-native context" to match the order of the Vault classes you list. Otherwise looks good.

2024-02-14 21:00 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/react/getting_started.md
> +We can manually lock our vault, but it would be nice if the vault locked for us if the application was in the background for a period of time. We can accomplish this by doing two actions when initial
I might adjust it to:
>We can manually lock our vault, but it would be nice if the vault locked for us automatically. This can be accomplished by setting [lockAfterBackgrounded](https://ionic.io/docs/identity-vault/interfaces/identityvaultconfig#lockafterbackgrounded), which will lock the vault when the application is resumed provided the app was backgrounded for the configured amount of time.

2024-02-14 21:29 UTC, jon-ionic commented on docs/native-solutions/identity-vault/react/getting_started.md
> +We can manually lock our vault, but it would be nice if the vault locked for us if the application was in the background for a period of time. We can accomplish this by doing two actions when initial
Sounds great, thanks! I'll have the Vue and Angular docs updated on my next PR as well.