feat(IV): add the device API tutorial for Angular
ionic-enterprise/tutorials pull request #33
Opened 2024-02-13 17:52 UTC by kensodemann

2024-02-13 20:53 UTC, eric-horodyski requested changes

2024-02-13 20:53 UTC, eric-horodyski commented on docs/native-solutions/identity-vault/angular/device-api.md
> +When we created our other tutorials we implemented several pieces of functionality without taking the capabilities and
I would replace "When we created our other tutorials" with something like "When we created our other applications". The first time I read it I thought it was saying something to the effect of "When Ionic wrote our other tutorials".

2024-02-13 20:53 UTC, eric-horodyski commented on docs/native-solutions/identity-vault/angular/device-api.md
> +- Enabling or disables various functionality based on the capabilities of the device.
Should read "Enabling or disabling"

2024-02-13 20:53 UTC, eric-horodyski commented on docs/native-solutions/identity-vault/angular/device-api.md
> +We have have an example of doing this within the `Tab2Page` where button that initiates the "Show Biometric Prompt"
Should read "where the button"

2024-02-13 20:53 UTC, eric-horodyski commented on docs/native-solutions/identity-vault/angular/device-api.md
> +Using this code as a model, add similar functionality to to the "Use Biometrics" button on the `Tab1Page`.
Remove the duplicate "to" so it reads: "functionality to the"

2024-02-13 20:53 UTC, eric-horodyski commented on docs/native-solutions/identity-vault/angular/device-api.md
> +  - If there no system passcode force the user to log in time.
Should read "force the user to log in each time"

2024-02-13 20:53 UTC, eric-horodyski commented on docs/native-solutions/identity-vault/angular/device-api.md
> +Add a private `provisionBiometrics()`. Display the biometric prompt if permissions need to be prompted.
Should read "Add a private method"

2024-02-14 14:32 UTC, kensodemann commented on docs/native-solutions/identity-vault/angular/device-api.md
> +When we created our other tutorials we implemented several pieces of functionality without taking the capabilities and
Updated wording to be more clear. Please check if the new wording is OK.

2024-02-14 14:34 UTC, kensodemann commented on docs/native-solutions/identity-vault/angular/device-api.md
> +- Enabling or disables various functionality based on the capabilities of the device.
Updated.

2024-02-14 14:38 UTC, kensodemann commented on docs/native-solutions/identity-vault/angular/device-api.md
> +We have have an example of doing this within the `Tab2Page` where button that initiates the "Show Biometric Prompt"
added the "the"

2024-02-14 14:40 UTC, kensodemann commented on docs/native-solutions/identity-vault/angular/device-api.md
> +Using this code as a model, add similar functionality to to the "Use Biometrics" button on the `Tab1Page`.
removed the extra 'to'

2024-02-14 15:06 UTC, kensodemann commented on docs/native-solutions/identity-vault/angular/device-api.md
> +  - If there no system passcode force the user to log in time.
Added the 'each'

2024-02-14 15:09 UTC, kensodemann commented on docs/native-solutions/identity-vault/angular/device-api.md
> +Add a private `provisionBiometrics()`. Display the biometric prompt if permissions need to be prompted.
I liked "Add a private method called `pro...`" better, so I changed it as such.

2024-02-14 16:22 UTC, eric-horodyski approved these changes

2024-02-14 22:45 UTC, jameson-w-taylor requested changes

2024-02-14 22:45 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/angular/device-api.md
> +- `showBiometricPrompt`: Show a biometric prompt to the user. This method will resolve when the user dismisses
Should this say "successfully provides biometrics" instead of "dismisses"?

2024-02-14 22:45 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/angular/device-api.md
> +- Handle setting permissions on iOS devices that use Face ID.
Should this be "Handle getting permission"?

2024-02-14 22:45 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/angular/device-api.md
> +    >
The formatting of the tags here is odd, I'd expect the ">" in front of "Show Biometric Prompt" to be at the end of the previous line. And the closing "</ion-button" to be on the next line with it's closing ">"

2024-02-14 22:45 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/angular/device-api.md
> +Change the `type` to be `InMemory` and increase the background lock time from 2 seconds to 30 seconds.
I'm probably just assuming these 2 changes are related to each other, but it feels a little confusing to combine them in a single step since `lockAfterBackgrounded` has no effect for `InMemory` Vaults. This might cause some folks to conflate the two and maybe develop an incorrect impression this works with this type of Vault.

2024-02-14 22:45 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/angular/device-api.md
> +    const type =
I had brought this up on the PR from Jon, but I think the nested ternary is doing more harm than good here.
Feel free to ignore it, but something a bit more expanded might help readability and may be easier for newcomers to visually see what we're accomplishing here.

```ts
async updateUnlockMode(mode: UnlockMode): Promise<void> {
  const newConfig = { ...(valut.config as IdentityVaultConfig) };

  switch (mode) {
    case 'BiometricsWithPasscode': {
      newConfig.type = VaultType.DeviceSecurity;
      newConfig.deviceSecurityType = DeviceSecurityType.Both;
      break;
    }
    case 'InMemory': {
      newConfig.type = VaultType.InMemory;
      newConfig.deviceSecurityType = DeviceSecurityType.None;
      break;
    }
    default: {
      newConfig.type = VaultType.SecureStorage;
      newConfig.deviceSecurityType = DeviceSecurityType.None;
      break;
    }
  }

  await vault.updateConfig(newConfig);
}
```

2024-02-14 22:45 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/angular/device-api.md
> +    const lockAfterBackgrounded = type === VaultType.InMemory ? 30000 : 2000;
As mentioned earlier, `lockAfterBackgrounded` has no effect for `InMemory` Vaults so it's strange to use this Vault type to configure a value for it.

2024-02-14 22:45 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/angular/device-api.md
> +  is restarted or is put in the background for more than 30 seconds.
Am I wrong about `InMemory` Vaults and `lockAfterBackgrounded`? Our [docs](https://ionic.io/docs/identity-vault/enums/vaulttype#inmemory) say it should have no effect.

2024-02-15 13:24 UTC, kensodemann commented on docs/native-solutions/identity-vault/angular/device-api.md
> +- Handle setting permissions on iOS devices that use Face ID.
Well, we are doing both getting and setting I guess...
"Managing permissions..." maybe?

2024-02-15 13:25 UTC, kensodemann commented on docs/native-solutions/identity-vault/angular/device-api.md
> +    >
You will need to complain to the "prettier" team... lol

2024-02-15 13:28 UTC, kensodemann commented on docs/native-solutions/identity-vault/angular/device-api.md
> +    const type =
This is too big to change here as the change would need to _start_ in the getting started tutorial and trickle over to the other ones.

I'll create Jira tickets for that.

2024-02-15 13:32 UTC, kensodemann commented on docs/native-solutions/identity-vault/angular/device-api.md
> +    const lockAfterBackgrounded = type === VaultType.InMemory ? 30000 : 2000;
If you want to see the effect, leave it at `2000` and put the app in the background.

The session will be cleared after 2 seconds in the background. So it doesn't technically 'lock' but it does clear out the vault.

2024-02-15 13:32 UTC, kensodemann commented on docs/native-solutions/identity-vault/angular/device-api.md
> +  is restarted or is put in the background for more than 30 seconds.
The docs are misleading.

2024-02-15 13:37 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/angular/device-api.md
> +  is restarted or is put in the background for more than 30 seconds.
good to know

2024-02-15 15:57 UTC, kensodemann commented on docs/native-solutions/identity-vault/angular/device-api.md
> +- Handle setting permissions on iOS devices that use Face ID.
So changed

2024-02-15 15:58 UTC, kensodemann commented on docs/native-solutions/identity-vault/angular/device-api.md
> +  is restarted or is put in the background for more than 30 seconds.
I have created a PR on the docs.

2024-02-15 16:58 UTC, jameson-w-taylor commented on docs/native-solutions/identity-vault/angular/device-api.md
> +    >
So sad, alright ship it!

2024-02-20 13:39 UTC, merged