feat: android security provider
ionic-enterprise/tutorials pull request #36
Opened 2024-02-26 19:08 UTC by dtarnawsky

2024-02-27 14:06 UTC, jameson-w-taylor requested changes

2024-02-27 14:06 UTC, jameson-w-taylor commented on docs/mobile-security/android-security-provider.md
> +const result = await CapacitorSecurityProvider.installIfNeeded();
Given the context later on about how this has no effect on iOS, maybe adjusting this snippet to wrap it in platform detection might simplify the conditional? Just personal preference so feel free to ignore this opinion.

Something like:
```ts
import { CapacitorSecurityProvider, SecurityProviderStatus } from '@capacitor-community/security-provider';

if (Capacitor.getPlatform() === 'android') {
  const { status } = await CapacitorSecurityProvider.installIfNeeded();
  if (status !== SecurityProviderStatus.Success) {
    // Do not proceed. The Android Security Provider failed to verify / install.
  }
}
```

2024-02-27 14:06 UTC, jameson-w-taylor commented on docs/mobile-security/android-security-provider.md
> +Android relies on a security provider for secure network communications. However, from time to time, vulnerabilities are found in the default security provider. To protect against these vulnerabiliti
Maybe add link for "security provider":
>...relies on a security [Provider](https://developer.android.com/reference/java/security/Provider) for...

2024-02-27 14:47 UTC, dtarnawsky commented on docs/mobile-security/android-security-provider.md
> +Ensuring that your App verifies that you are using the latest secure version of Play Services is an additional step in ensuring the security of your Capacitor application.
Thanks, updated.

2024-02-27 14:49 UTC, dtarnawsky commented on docs/mobile-security/android-security-provider.md
> +const result = await CapacitorSecurityProvider.installIfNeeded();
The check for result.status !== SecurityProviderStatus.NotImplemented handles this for web and iOS. I guess a personal preference thing but I like the JS code base to have as few platform conditional as possible.

2024-02-27 14:49 UTC, dtarnawsky commented on docs/mobile-security/android-security-provider.md
> +Android relies on a security provider for secure network communications. However, from time to time, vulnerabilities are found in the default security provider. To protect against these vulnerabiliti
Thanks, updated

2024-02-27 15:39 UTC, jameson-w-taylor approved these changes

2024-02-28 20:13 UTC, eric-horodyski approved these changes
One suggestion to make a sentence flow better, but not critical. Otherwise, LGTM.

2024-02-28 20:13 UTC, eric-horodyski commented on docs/mobile-security/android-security-provider.md
> +In the startup of your application you should check if an update to the security provider is needed by adding the following code:
I would reword this sentence to flow better:

> In your application's startup code, check if an update to the security provider is needed by adding the following code:

2024-02-28 20:52 UTC, merged