feat(AC): add the react getting started guide
ionic-enterprise/tutorials pull request #6
Opened 2023-10-25 18:04 UTC by kensodemann

2023-10-25 18:54 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/react/getting-started.md
> +```typescript session-store.ts
What's your opinion on using the fully qualified path name here, `src/utils/session-store.ts`, as opposed to just `session-store.ts`?

2023-10-25 18:54 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/react/getting-started.md
> +Eventually, this store will be used with a [useSyncExternalHook](https://react.dev/reference/react/useSyncExternalStore) hook. Because of this, we need some boilerplate code starting with a `subscrib
I would underscore that we use `useSyncExternalHook` to sync `session` with React. Maybe something like this?

> To sync the store with React, we will eventually use `useSyncExternalHook`. In preparation, we need some boilerplate code starting with a `subscribe()` method.

2023-10-25 18:54 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/react/getting-started.md
> +
There are several ways React developers can implement state management:
1. Should we explicitly call this out, or is it a reasonable assumption that the reader should refactor this into their own state management library in their production app?
2. If we do call this out, it's a meta-callout that would need to be expressed for many React tutorials.

My opinion is skewed by past experience and would like to hear what @jameson-w-taylor and @rjtwohey think.

2023-10-25 18:57 UTC, kensodemann commented on docs/native-solutions/auth-connect/react/getting-started.md
> +```typescript session-store.ts
I have actually been wondering that myself...

2023-10-25 19:00 UTC, kensodemann commented on docs/native-solutions/auth-connect/react/getting-started.md
> +
My opinion: I would _like_ to think it is a reasonable assumption, but I have also seen (some of) our customers for which "reasonable assumptions" are not reasonable.

2023-10-25 19:04 UTC, jameson-w-taylor commented on docs/native-solutions/auth-connect/react/getting-started.md
> +const isNative = isPlatform('hybrid');
I know there is a couple of ways to do a check like this, but I wanted to add my 2 cents.
Personally I prefer to use the Capacitor [utility](https://capacitorjs.com/docs/core-apis/web#isnativeplatform) to check for this, and it might be nice to do in our samples because it'd be consistent across examples.
But this is a very small point and has no real impact on anything.

2023-10-25 19:07 UTC, jameson-w-taylor commented on docs/native-solutions/auth-connect/react/getting-started.md
> +For the `login()`, we need to pass both the `provider` and the `authOptions` we established earlier. It restores an `AuthResult` that we need to store. Be sure to export the function so we can use it
"It restores an AuthResult..." should be "It returns an..."

2023-10-25 19:13 UTC, kensodemann commented on docs/native-solutions/auth-connect/react/getting-started.md
> +const isNative = isPlatform('hybrid');
I am not sure on all of the samples, but all of the Vue ones I have written use `isPlatform` from the framework.

My biggest question would be is the Capacitor utility function easier or harder to mock?

2023-10-25 19:16 UTC, rjtwohey commented on docs/native-solutions/auth-connect/react/getting-started.md
> +
I tend to agree that while it is a reasonable assumption that doesn't necessarily mean calling it out is a bad thing either in a guide. Even if I know and understand something I prefer that tutorials make as few assumptions as possible because in the end you just never know. However, that becomes another topic of avoiding being overly verbose.

2023-10-25 19:16 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/react/getting-started.md
> +```typescript session-store.ts
The rule I've been following is that as long as it doesn't degrade the readability I keep the entire path. I think it truncates after a certain number of characters; it certainly does when you have multiple file tabs.

2023-10-25 19:28 UTC, rjtwohey commented on docs/native-solutions/auth-connect/angular/getting-started.md
> +The user can perform login and logout operations, but if the browser is refreshed, the application loses the `AuthResult`. This value needs to be persisted between sessions of the application. To fix
Meant to just leave this as a comment and not a review - is it worth linking to a demo that combines IV and AC? I think it could be helpful to customers looking for ways to do both instead of just trying to mesh together two different getting started guides.

2023-10-25 19:31 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/react/getting-started.md
> +const isNative = isPlatform('hybrid');
I agree w/ @jameson-w-taylor here. If we could demonstrate orchestrating Auth Connect without using the Ionic Framework I think that would be the best look and something we can point to for customers who come to us with apps not built using the framework.

2023-10-25 19:38 UTC, jameson-w-taylor commented on docs/native-solutions/auth-connect/react/getting-started.md
> +
My opinion is that we're intentionally avoiding any 3rd party state management, so anything more detailed than saying "your state management approach may be different (potentially significantly), but that topic is outside the scope of this tutorial".

2023-10-25 19:42 UTC, jameson-w-taylor commented on docs/native-solutions/auth-connect/react/getting-started.md
> +const isNative = isPlatform('hybrid');
I prefer it because I think it reads better, and doesn't rely on the specific app framework (unlikely, but it's "safe" to assume an app will stay on Capacitor but might refactor from one framework to another). In areas where I have multiple options for the same result I like to rely on dependencies that are less likely to change in my project.

2023-10-25 19:50 UTC, jameson-w-taylor requested changes
I left some inline comments, I find it weird that Github requires a comment when I submit the review as well.

2023-10-29 11:11 UTC, kensodemann commented on docs/native-solutions/auth-connect/react/getting-started.md
> +Eventually, this store will be used with a [useSyncExternalHook](https://react.dev/reference/react/useSyncExternalStore) hook. Because of this, we need some boilerplate code starting with a `subscrib
Done.

2023-10-29 11:26 UTC, kensodemann commented on docs/native-solutions/auth-connect/react/getting-started.md
> +
added a note

2023-10-29 11:30 UTC, kensodemann commented on docs/native-solutions/auth-connect/angular/getting-started.md
> +The user can perform login and logout operations, but if the browser is refreshed, the application loses the `AuthResult`. This value needs to be persisted between sessions of the application. To fix
There will eventually be one in the mono-repo where the demos and tutorials are (actually, a couple).

We can link that in at that time if we remember.

Otherwise, it will likely be obvious enough to developers who are looking at the repo (if we forget to link it).

2023-10-29 11:31 UTC, kensodemann commented on docs/native-solutions/auth-connect/react/getting-started.md
> +For the `login()`, we need to pass both the `provider` and the `authOptions` we established earlier. It restores an `AuthResult` that we need to store. Be sure to export the function so we can use it
fixed

2023-10-29 11:31 UTC, kensodemann commented on docs/native-solutions/auth-connect/react/getting-started.md
> +```typescript session-store.ts
added the paths

2023-10-29 11:49 UTC, kensodemann commented on docs/native-solutions/auth-connect/react/getting-started.md
> +const isNative = isPlatform('hybrid');
TIL a new word... "bikeshedding"
Nice!

Anyhow, switched to the Capacitor utility.

As a general rule in the tutorials and demos then:
- if the demo is only using Ionic because it is convenient, use the Cap one
- if the demo is specifically centered around Ionic or otherwise very much relies on Ionic, use whichever one you want

2023-11-01 13:39 UTC, rjtwohey approved these changes

2023-11-01 13:43 UTC, jameson-w-taylor approved these changes

2023-11-01 23:41 UTC, merged