Finished "Fix android launch From Home" Page
ionic-enterprise/tutorials pull request #7
Opened 2023-11-10 20:43 UTC by tomionic

This page should be finished, the only thing left to do regarding this page would be to set it lower in the sidebar options. Created from https://ionic-cloud.atlassian.net/browse/CSEE-587 and https://ionic.io/docs/auth-connect/android-launch-from-home.

2023-11-14 20:58 UTC, eric-horodyski requested changes

2023-11-14 20:58 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/fix-android-launch.md
> +When launched on an Android device, your application will startup and display the webview your application is served in. However, for Auth Connect this may not be the behavior you want when a user is
Could you elaborate on this paragraph? I'm confused at this part:

> this may not be the behavior you want when a user is on the login page: you will likely want your application to return to the login page.

2023-11-14 20:58 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/fix-android-launch.md
> +Go to your Capacitor Android project and navigate to the directory that contains your application's package. For example, if your app's package name is `io.ionic.starter`, the path might be something
> the path might be something like `android/app/src/main/java/io/ionic/starter/`.

Rephrase this and write the actual path, for example:

> the path will be `android/app/src/main/io/ionic/starter`

2023-11-14 20:58 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/fix-android-launch.md
> +Created and new Java file in this folder named `LauncherActivity.java`.
Created and -> Create a

2023-11-14 20:58 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/fix-android-launch.md
> +<CH.Scrollycoding>
Use a single `<CH.Scrollycoding>` component. When a new file is referenced, it will create and switch to a new tab in the existing `<CH.Scrollycoding>` component.

2023-11-14 20:58 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/fix-android-launch.md
> +Navigate to the `AndroidManifest.xml` file which should be located at the following file path `android/app/src/main/` and locate the activity section.
which should be located -> which is located

2023-11-14 20:58 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/fix-android-launch.md
> +Update the `AndroidManifest.xml` to set the new Activity as the launcher activity. Add an intent-filter to LauncherActivity to define it as the launcher.
Update the `AndroidManifest.xml` -> Update `AndroidManifest.xml`. Put `intent-filter` and `LauncherActivity` in backticks to render them as preformatted words.

2023-11-14 20:58 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/fix-android-launch.md
> +Remove the intent-filter on the MainActivity that previously defined it as the launcher. Make sure to keep the MainActivity launchMode as `singleTask`.
Add backticks to: `intent-filter`, `MainActivity`, `launchMode`.

2023-11-14 20:58 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/fix-android-launch.md
> +On the MainActivity change exported to `false` and make sure to keep launchMode as `singleTask`.
Add backticks to: `MainActivity`, `launchMode`.

2023-11-14 20:58 UTC, eric-horodyski commented on docs/native-solutions/auth-connect/fix-android-launch.md
> +Be sure to run `npx cap sync` after applying these changes.
Expand on the conclusion: 

> Be sure to run `npx cap sync` after applying these changes, run the Android application, and notice that [FILL IN BEHAVIOR CHANGED]

2023-11-16 19:35 UTC, kensodemann commented on docs/native-solutions/auth-connect/fix-android-launch.md
> +When launched on an Android device, your application will startup and display the webview your application is served in. However, for Auth Connect this may not be the behavior you want when a user is
To be fair, that was taken directly from here: https://ionic.io/docs/auth-connect/android-launch-from-home

We should probably brainstorm on how to word this. Partially, this will involve trying it with and without the change. I think what the difference is pertains to how the app acts when backgrounded while doing a login.

2023-11-16 19:37 UTC, kensodemann commented on docs/native-solutions/auth-connect/fix-android-launch.md
> +Go to your Capacitor Android project and navigate to the directory that contains your application's package. For example, if your app's package name is `io.ionic.starter`, the path might be something
I like the "something like" better because it won't necessarily be that exact path. Specifically the `io/ionic/starter` part of the path will very likely be different, at least if the customer picked a reasonable bundle ID, so perhaps this should just be something that is better explained.

2023-11-16 19:38 UTC, kensodemann commented on docs/native-solutions/auth-connect/fix-android-launch.md
> +<CH.Scrollycoding>
I agree. That is _actually_ what I came here to comment on...

2023-11-16 19:39 UTC, kensodemann commented on docs/native-solutions/auth-connect/fix-android-launch.md
> +Be sure to run `npx cap sync` after applying these changes.
This is the other bit I was going to note. This will also help the scrolly coding scroll to the last bit.

2023-12-06 22:53 UTC, tomionic commented
Pushed the latest changes to this fix-android-launch this pull request is now ready for re-review

2023-12-07 18:42 UTC, eric-horodyski requested changes
LGTM after the one grammar fix.

2023-12-07 19:29 UTC, kensodemann approved these changes
LGTM

2023-12-08 23:51 UTC, merged