docs(portals): web initial context step
ionic-enterprise/tutorials pull request #9
Opened 2023-11-15 17:31 UTC by eric-horodyski

Looking for a review of the content in `initial-context.md`

2023-11-20 15:00 UTC, kensodemann requested changes

2023-11-20 15:00 UTC, kensodemann commented on docs/portals/training/web/02-initial-context.md
> +Initial context is useful when you want to pass authentication information, navigate to a specific path, or any case where having data _before_ the web application loads would prevent re-renders or U
This sentence reads weirdly. It may be best in some other order such as:

"Initial context is useful for any use-case where having data _before_ the web application loads prevents re-renders or UI jank. For example, it can be used to pass authentication information or to navigate to a specific path."

2023-11-20 15:00 UTC, kensodemann commented on docs/portals/training/web/02-initial-context.md
> +In order to obtain the session, the _Expenses_ web application needs to pass authentication tokens to an API endpoint that returns session information. Those tokens are passed as initial context from
This paragraph and the next seem like a lot of up-front text. I would shorten these two paragraphs to something like:

```
In this exercise, we will learn:
- How to use Initial Context to pass the Authentication information from the native app to the Portals web app.
- How to stub the Initial Context within the web application's development workflow.
```

2023-11-20 15:00 UTC, kensodemann commented on docs/portals/training/web/02-initial-context.md
> +The _Expenses_ web application needs the user's session information (specifically the user ID) in order to call the expenses backend such that it only returns their expenses. Failing to provide a use
This whole backend seems _horribly_ non-secure, but ok... I guess it is mostly for illustration. :)

2023-11-20 15:00 UTC, kensodemann commented on docs/portals/training/web/02-initial-context.md
> +Stubbing the initial context is a pretty straightforward procedure. Modify `initial-context.ts` to add the highlighted code below:
This is where I would add the information on _why_ you would want to stub the context (see prior comment where I suggested shortening to a bullet point, basically add the previous detailed info here).

2023-11-27 16:11 UTC, eric-horodyski commented on docs/portals/training/web/02-initial-context.md
> +Initial context is useful when you want to pass authentication information, navigate to a specific path, or any case where having data _before_ the web application loads would prevent re-renders or U
👍

2023-12-05 18:02 UTC, closed without merging

2023-12-05 18:03 UTC, eric-horodyski commented
Closing in favor of a wholistic review of the web training (#13)